export const CARS=[
    {
        id:1,
        name:'BMW',
        price:30000,
        year:2010,
        color:'red',
        description:'BMW is a German automobile manufacturer',
        isSold:false,
        createdAt:new Date(),
        updatedAt:new Date(),
    },
    {
        id:2,
        name:'Audi',
        price:40000,
        year:2011,
        color:'blue',
        description:'Audi is a German automobile manufacturer',
        isSold:false,
        createdAt:new Date(),
        updatedAt:new Date(),
    },
    {
        id:3,
        name:'Mercedes',
        price:50000,
        year:2012,
        color:'black',
        description:'Mercedes is a German automobile manufacturer',
        isSold:false,
        createdAt:new Date(),
        updatedAt:new Date(),
    },
    {
        id:4,
        name:'BMW',
        price:30000,
        year:2010,
        color:'red',
        description:'BMW is a German automobile manufacturer',
        isSold:false,
        createdAt:new Date(),
        updatedAt:new Date(),
    }
]